const list = [
    {
      id: 1,
     
      title: "Chicken Curry Cut ",
      pack: "The  pack for a big, delicious curry ",
      qty:'500g',
      pices:'12-18 Pieces',
      serves:'Serves 4',
      price:250,
      img: "https://chikplaza.com/wp-content/uploads/2017/08/Chicken-Whole-Curry-Cut_STP3528.jpg",
      amount: 1,
    },
    {
      id: 2,
      title: "Chicken Drumstick ",
      pack: "Juicy bone-in chicken drumsticks",
      qty:'500g',
      pices:'4 Pieces',
      serves:'Serves 3-4',
      price: 450,
      img: "https://tse1.mm.bing.net/th?id=OIP.pZZYwvy4VRLiawsZwZNXHgHaFs&pid=Api&rs=1&c=1&qlt=95&w=144&h=110",
      amount: 1,
    },
    {
      id: 3,
      title: "Chicken Breast ",
      pack: "tender boneless chicken thighs",
      qty:'500g',
      pices:'3-5 Pieces',
      serves:'Serves 2-4',
      price: 399,
      img: "https://tse1.mm.bing.net/th?id=OIP.wYJofPfhMV_eW-ryd5REXgHaE8&pid=Api&rs=1&c=1&qlt=95&w=152&h=101",
      amount: 1,
    },
    {
      id: 4,
      title: "Chicken Lollipop ",
      pack: " 7pieces of  chicken lollipops",
      qty:'500g',
      pices:'7 Pieces',
      serves:'Serves 5',
      price: 250,
      img: "https://tse1.mm.bing.net/th?id=OIP.R9sX4nV5_xUAZzE--SN_kAHaE2&pid=Api&rs=1&c=1&qlt=95&w=191&h=124",
      amount: 1,
    },
    {
      id: 5,
      title: "Chicken -Keema",
      pack: " Keema is made from fresh ",
      qty:'500g',
      pices:'40-70 ',
      serves:'Serves 5',
      price: 290,
      img: "https://tse1.mm.bing.net/th?id=OIP.-VJfNu-19TxoRYIdBNhzZAHaE8&pid=Api&rs=1&c=1&qlt=95&w=146&h=97",
      amount: 1,
    },
    {
      id: 6,
      title: "Chicken Liver",
      pack: "They are perfect in Liver Curry.",
      qty:'500g',
      pices:'10-11 Pieces',
      serves:'Serves 2-3',
      price: 155,
      img: "https://tse1.mm.bing.net/th?id=OIP.BiFGBTX6rNFQzNmIrzzNXwAAAA&pid=Api&rs=1&c=1&qlt=95&w=183&h=122",
      amount: 1,
    },

    
    {
      
      id: 7,
      title: "Mutton Curry Cut",
      pack: "Fat-rich pieces that render into flavorful curries.",
      qty:'500g',
      pices:'10-15 Pieces',
      serves:'Serves 3-5',
      price: 650,
      img: "https://tse2.mm.bing.net/th?id=OIP.-IizRi9g84vGHgFQLTdTwwAAAA&pid=Api&P=0&h=180",
      amount: 1,
     
    },
    {
      
      id: 8,
      title: "Mutton Liver ",
      pack: " Cut & cleaned Mutton Liver for pan-fried dishes.",
      qty:'500g',
      pices:'22-25 Pieces',
      serves:'Serves 4-5',
      price: 320,
      img: "https://www.meathouseindia.com/wp-content/uploads/2020/06/mutton-liver.jpg",
      amount: 1,
    },
    {
      id: 9,
      title: "Mutton Bonless",
      pack: "Bbite-sized fat-trimmed cuts for pan-fried delicacies.",
      qty:'500g',
      pices:'10-13 Pieces',
      serves:'Serves 2-3',
      price: 155,
      img: "https://tse2.mm.bing.net/th?id=OIP.IL728Spvi8N1hMvK32sMPwHaFm&pid=Api&P=0&h=180",
      amount: 1,
    },
    {
      id: 10,
      title: "Mutton Keema",
      pack: "Finely ground goat mince for curries, kebabs & more.",
      qty:'500g',
      pices:'30-35 Pieces',
      serves:'Serves 2-3',
      price: 660,
      img: "https://chikplaza.com/wp-content/uploads/2017/09/Mutton-Keema_STP3615.jpg",
      amount: 1,
    },
    {
      id: 11,
      title: "Mutton Shoulder Curry ",
      pack: "The meatiest cut for fall off the bone Mutton curries.",
      qty:'500g',
      pices:'12-15 Pieces',
      serves:'Serves 4-5',
      price: 799,
      img: "https://chikplaza.com/wp-content/uploads/2017/09/Mutton-Mix-Assorted-Curry-Cut_STP3627.jpg",
      amount: 1,
    },
    
    {
      id: 12,
      title: "Mutton Kidney Curry",
      pack: "Neatly halved kidneys for pan-fried & grilled dishes",
      qty:'500g',
      pices:'4-6 Pieces',
      serves:'Serves 4-5',
      price: 320,
      img: "https://tse4.mm.bing.net/th?id=OIP.piVDcUljv0MDRaAh-qnEtgHaD6&pid=Api&P=0&h=180",
      amount: 1,
    },

    {
      id: 13,
     
      title: "Korameenu Fish ",
      pack: "Murrel is also known by many other names such as Korameenu,",
      qty:'500g',
      pices:'12-18 Pieces',
      serves:'Serves 4',
      price:250,
      img: "https://tse2.explicit.bing.net/th?id=OIP.NZJ7b4nvKkrOXAdRke2_LwHaGN&pid=Api&P=0&h=180",
      amount: 1,
    },
    {
      id: 14,
      title: "Indian Salmon ",
      pack: "Uniform steaks for curries & fry-up",
      qty:'500g',
      pices:'4-7 Pieces',
      serves:'Serves 2-4',
      price: 850,
      img: "https://tse4.mm.bing.net/th?id=OIP.Z_8rqOOa_6CP1v2i0LR2cwHaE8&pid=Api&P=0&h=180",
      amount: 1,
    },
    {
      id: 15,
      title: "Vanjaram ",
      pack: "The fish has only one centre bone easily removed once cooked",
      qty:'500g',
      pices:'9-14 Pieces',
      serves:'Serves 3-4',
      price: 499,
      img: "https://tse2.mm.bing.net/th?id=OIP.O1fqXFlkJ27hKQWPz7HDUgHaEv&pid=Api&P=0&h=180",
      amount: 1,
    },
    {
      id: 16,
      title: "White Pomfret  ",
      pack: " The fish is very tender upon cooking and is often served fried",
      qty:'500g',
      pices:'3-5 Pieces',
      serves:'Serves 2-4',
      price: 450,
      img: "https://tse4.mm.bing.net/th?id=OIP.efGEdCYxQCuu1zyTZBNADAHaHa&pid=Api&P=0&h=180",
      amount: 1,
    },
    {
      id: 17,
      title: "Pink Perch",
      pack: " As this fish is mildly sweet with a soft texture ",
      qty:'500g',
      pices:'4-6 ',
      serves:'Serves 4',
      price: 390,
      img: "https://tse1.mm.bing.net/th?id=OIP.8-Mc0nmjF433L0q4KPVPUQAAAA&pid=Api&P=0&h=180",
      amount: 1,
    },
    {
      id: 18,
      title: "Roopchand",
      pack: "A special steak cut from the highest quality Roopchand fish.",
      qty:'500g',
      pices:'6-9 Pieces',
      serves:'Serves 4-6',
      price: 399,
      img: "https://tse4.mm.bing.net/th?id=OIP.91soOiyNLktwzH7zgmuFagHaHa&pid=Api&P=0&h=180",
      amount: 1,
    },
    {
      id: 19,
      
      title: "White Prawns   ",
      pack: "They are cleaned and deveined and can go straight from the pack to your pan.",
      qty:'350g',
      pices:'25-40 Pieces',
      serves:'Serves 4-5',
      price:459,
      img: "https://tse1.mm.bing.net/th?id=OIP.a8el41rr-LDBSK3xdmAlPQHaHa&pid=Api&P=0&h=180",
      amount: 1,
    },
    {
      id: 20,
      title: "Tiger Prawns Large ",
      pack: "they are super juicy and become tender when cooked",
      qty:'500g',
      pices:'40-45 Pieces',
      serves:'Serves 3-5',
      price: 650,
      img: "https://tse1.mm.bing.net/th?id=OIP.tz-D_9tC0UAaGjLX4VUnxgHaE8&pid=Api&P=0&h=180",
      amount: 1,
    },
    {
      id: 21,
      title: "Sea White Prawns  ",
      pack: "Fresh prawns for grills, curries & more",
      qty:'500g',
      pices:'35-40 Pieces',
      serves:'Serves 3-4',
      price: 599,
      img: "https://tse4.mm.bing.net/th?id=OIP.1bI9IwrSbbDssnQOiY7sdwHaE2&pid=Api&P=0&h=180",
      amount: 1,
    },
    {
      id: 22,
      title: "Flower Shrimp Prawns ",
      pack: " Commonly used in South Indian & South East Asian cuisine",
      qty:'350g',
      pices:'30-45 Pieces',
      serves:'Serves 2-4',
      price: 580,
      img: "https://tse2.mm.bing.net/th?id=OIP.RY3kKMMz9HW7xltludKTeAHaE8&pid=Api&P=0&h=180",
      amount: 1,
    },
    {
      id: 23,
      title: "Poovalan Prawns",
      pack: " Mostly found around the coasts of Calicut, these golden-brown Poovallan Prawns ",
      qty:'300g',
      pices:'4-6 ',
      serves:'Serves 4',
      price: 500,
      img: "https://tse3.mm.bing.net/th?id=OIP.UqhSt_MKn1b6p2lhU7m3vwHaF7&pid=Api&P=0&h=180",
      amount: 1,
    },
    {
      id: 24,
      title: "Seawater Prawns",
      pack: "these small sized prawns absorb spices quite well.",
      qty:'300g',
      pices:'6-9 Pieces',
      serves:'Serves 4-6',
      price: 399,
      img: "https://tse1.mm.bing.net/th?id=OIP.V0PQ_V309wAZlgHLllpCugHaHa&pid=Api&P=0&h=180",
      amount: 1,
    },

    {
      id: 25,
     
      title: "Farm Fresh Eggs   ",
      pack: "Farm-fresh eggs are from feed-controlled hens, raised on biosecure farms.",
      
      pices:'6 Pieces',
      serves:'Serves 5-6',
      price:85,
      img: "https://tse2.mm.bing.net/th?id=OIP.QLPJTZoE18W5PWl1j5dTWAHaEj&pid=Api&P=0&h=180",
      amount: 1,
    },
    {
      id: 26,
      title: "Brown Eggs-6 pack  ",
      pack: " brown-shelled eggs come from feed-controlled hens",
      
      pices:'6 Pieces',
      serves:'Serves 5-6',
      price: 90,
      img: "https://tse2.explicit.bing.net/th?id=OIP.xELFKB-r9o4d1eRtzU5PbgHaFb&pid=Api&P=0&h=180",
      amount: 1,
    },
    {
      id: 27,
      title: "Brown Eggs-12 pack  ",
      pack: " brown-shelled eggs come from feed-controlled hens",
      
      pices:'12 Pieces',
      serves:'Serves 10-12',
      price: 185,
      img: "https://tse4.mm.bing.net/th?id=OIP.h1qAOYtALer8c6Sp1CHI-AHaFj&pid=Api&P=0&h=180",
      amount: 1,
    },
    {
      id: 28,
      title: "Omega 3 Eggs  ",
      pack: " Naturally rich in protein, these farm-fresh",
     
      pices:'6 Pieces',
      serves:'Serves 3-5',
      price: 120,
      img: "https://tse3.mm.bing.net/th?id=OIP.X9rkfgNcLWhhy2wK-RRI9AHaE8&pid=Api&P=0&h=180",
      amount: 1,
    },
    {
      id: 29,
      title: "Quail Eggs-6 pack",
      pack: " these speckle-shelled, small-sized eggs have a unique flavour ",
     
      pices:'6 ',
      serves:'Serves 5-6',
      price: 95,
      img: "https://tse3.mm.bing.net/th?id=OIP.dnqUHLPMoh7g1DspT1dBKwHaFP&pid=Api&P=0&h=180",
      amount: 1,
    },
    {
      id: 30,
      title: "Cage Free Brown Eggs",
      pack: "special farm-fresh eggs come from hens that are not inside battery cages.",
      
      pices:'6 Pieces',
      serves:'Serves 4-6',
      price: 95,
      img: "https://tse2.mm.bing.net/th?id=OIP.UkpyZZEM-zmQycvXANIg5gHaFW&pid=Api&P=0&h=180",
      amount: 1,
    },

  
    
     
   

  ];

  

  export default list;
  